# Generated by Django 5.2.4 on 2025-07-25 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, choices=[('local', 'Local de gastronomía'), ('proveedor', 'Productos o Servicios para gastronómicos'), ('trabajador', 'Trabajador de la gastronomía')], max_length=20, null=True, verbose_name='Tipo de Usuario')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nombre o Razón Social')),
                ('cuit_cuil', models.CharField(blank=True, max_length=13, verbose_name='CUIT/CUIL')),
                ('contact_number', models.CharField(blank=True, max_length=20, verbose_name='Número de Contacto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
