# Generated by Django 5.2.4 on 2025-08-01 15:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título de la Oferta')),
                ('descripcion', models.TextField(verbose_name='Descripción del Puesto')),
                ('requisitos', models.TextField(verbose_name='Requisitos')),
                ('tipo_contrato', models.CharField(max_length=50, verbose_name='Tipo de Contrato')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('activa', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_empleo', to='inicio.cliente')),
            ],
        ),
    ]
