# Generated by Django 5.2.4 on 2025-08-01 15:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_ofertaempleo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje Adicional')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='inicio.ofertaempleo')),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='inicio.postulante')),
            ],
            options={
                'unique_together': {('oferta', 'postulante')},
            },
        ),
    ]
