# Generated by Django 5.2.4 on 2025-08-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_conversacion_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='conversacion',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='remitente',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='postulacion',
        ),
        migrations.DeleteModel(
            name='Conversacion',
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
