# Generated by Django 5.2.4 on 2025-07-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_profile_cuit_cuil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cuit_cuil',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='CUIT/CUIL'),
        ),
    ]
