# Generated by Django 5.2.4 on 2025-08-01 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inicio', '0003_alter_profile_cuit_cuil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre_negocio', models.CharField(max_length=255, verbose_name='Nombre del Negocio')),
                ('cuit', models.CharField(max_length=13, verbose_name='CUIT')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='clientes/fotos/', verbose_name='Foto de Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('cuil', models.CharField(max_length=13, verbose_name='CUIL')),
                ('presentacion', models.TextField(verbose_name='Presentación Personal')),
                ('cv', models.FileField(blank=True, null=True, upload_to='postulantes/cvs/', verbose_name='Currículum Vitae (.pdf o .docx)')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='postulantes/fotos/', verbose_name='Foto de Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre_empresa', models.CharField(max_length=255, verbose_name='Nombre de la Empresa')),
                ('cuit', models.CharField(max_length=13, verbose_name='CUIT')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Empresa')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='proveedores/fotos/', verbose_name='Foto de Perfil')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cuit_cuil',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('cliente', 'Cliente'), ('proveedor', 'Proveedor'), ('postulante', 'Postulante')], max_length=20, null=True, verbose_name='Tipo de Usuario'),
        ),
    ]
