# Generated by Django 5.2.4 on 2025-10-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_catalogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('respondido', 'Respondido'), ('descartado', 'Descartado')], default='pendiente', max_length=20)),
                ('categoria', models.CharField(choices=[('dueño', 'Dueño de negocio / encargado'), ('proveedor', 'Proveedor de servicios o productos'), ('gubernamental', 'Entidad gubernamental'), ('otro', 'Otro')], default='otro', max_length=20)),
            ],
        ),
    ]
